name: PhillyFirst.org
favicon: null
layout_spectrum: 0.0321
typography_spectrum: 0.11284
title: The first page
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#494949'
    - '#fefefe'
    - '#85a29c'
    - '#e8be96'
  brandStrength: 0.375
  lightness: 0.0034537985920906067
  saturation: 0.4375
  rhythmicContrast: 0.4192238624673337
purpose: []
